export const CONNECT4_PLAYER_1 = '#c22';
export const CONNECT4_PLAYER_2 = '#cc2';

export const CONNECT4_STATUS_DRAW = 'CONNECT4_STATUS_DRAW';
export const CONNECT4_STATUS_PLAYER1WIN = 'CONNECT4_STATUS_PLAYER1WIN';
export const CONNECT4_STATUS_PLAYER2WIN = 'CONNECT4_STATUS_PLAYER2WIN';
export const CONNECT4_STATUS_RUNNING = 'CONNECT4_STATUS_RUNNING';
